### ISSUE TITLE
Will I get a virus if I download GTS??

### ISSUE THREAD

**Issue by YEEmeme** [opentoonz/GTS#141]
**https://vimeo.com/328193286**

Video Description: gen:variant.Razy.468146

The first discovery was made. 
I actually opened it up and checked it out, and it's infected with the virus.intense fear

Download GTS.2.5.0.zip.
Several GTS.EXEGAgen:variant.Rasy.468146 virus is confirmed.

바이러스 검사 : virus scan
악성코드 : Malicious code

**Comment by masafumi-inoue** [comment]
VirusTotalのチェックでひっかからないようにソースコードを修正しました #142
