### ISSUE TITLE
HistogramのHueで値が固定位置に集中する

### ISSUE THREAD

**Issue by masafumi-inoue** [opentoonz/GTS#32]
Edit HSV MinMaxウインドウで、Hueのhistogram表示が、R-RG-G-GB-B-BR の各位置に集中する問題

**Comment by masafumi-inoue** [comment]
#### Hue histogram表示が固定位置に集中する理由について
例えば、(R G B)値が(0 0 1)や(255 254 254)等、RGB各値の差が「ゼロでなく」かつ「非常に小さい」場合に起こる。この場合、Hueの変化が、例えば(1 0 0)→(1 1 0)→(0 1 0)→(0 1 1)→(0 0 1)→(1 0 1)となり、離散的な位置となる、これはRGB各8bit量子化ダイナミックレンジの問題である。

**Comment by masafumi-inoue** [comment]
#### 解決方法と考察
(方法1) RGB各8biｔの量子化ダイナミックレンジを増やす
(考察) ダイナミックレンジを増やすのは限られた機種のスキャナーとなり、ユーザーが運用できない

(方法2) グレイスケールに近い色をHueで判別する重要性は低いものとして、ある程度の彩度の強いピクセル値のみ、Hueのヒストグラムに表示する方法
(考察)「ある程度の彩度の強いピクセル値」、の「ある程度」をどの様に設定すればよいのか分からない。LimitメニューのSaturationを選択して操作することで、彩度の範囲を限定し、「離散的な位置」になるのを抑えることはできる。

**Comment by masafumi-inoue** [comment]
#### 今後の方針
- 明確な解決方法は見つからない。
- この問題はユーザーからの問題定義ではなく、ユーザーにとっての重要項目にはなっていない。
- 上記(方法2)での解決が”ある程度"できているので、ひとまずこれで保留とする。
- 今後histogramをどの様に使っていくかを考察するときに解決方法を探っていくこととする。

**Comment by kogaki** [comment]
Hのヒストグラムではなく、HSの2次元ヒートマップで表示するUIも作るというのは如何でしょう

**Comment by masafumi-inoue** [comment]
現状のヒストグラムは1次元的ですから、2次元にすることで視覚的に見渡しよくなりますね。

さらに言えば、HSV3次元色立体を表示して、3次元空間の中で操作するとか、、、
これは、プログラムも、ユーザーが操作するのも難しくなりそうですが、、、

**Comment by shun-iwasawa** [comment]
すでに有るならすみません、スキャン画像からクリックした位置のピクセルの色を拾うような機能はあるのでしょうか。Hueヒストグラムは色鉛筆の色域を見つけるための指標でしょうから、拾った色のHue値が分かる機能があるだけでだいぶ作業が早いと思います。

**Comment by masafumi-inoue** [comment]
スポイト機能は今はありません。
機能として入れる予定はあるのですが、いつ作業するかは未定です。
